### ISSUE TITLE
Duplicate bundles between modern and full

### ISSUE THREAD

**Issue by rxaviers** [unicode-cldr/cldr-dates-full#2]
[unicode-cldr/cldr-json](https://github.com/unicode-cldr/cldr-json) says:

>  The "modern" packages, which contains the set of locales listed as modern coverage targets by the CLDR subcomittee, and the "full" package, which **contains the rest of the locales not in the modern** coverage listing.

Although, cldr-dates-full lists several bundles that are already present on cldr-dates-modern: https://gist.github.com/rxaviers/a762dc8f6b01fbd37301

**Comment by JCEmmons** [comment]
The README in cldr-json has already been updated yesterday to reflect this.

**Comment by rxaviers** [comment]
Thanks
